### PR TITLE
[wip] lxqt-sudo: new GUI frontend for sudo

### PR DESCRIPTION
**Pull request by palinek**
... continuation of lxde/lxqt-admin#22

closes lxde/lxqt#537

Issues to fix:
- [x] icon support (for now just limited to showing one standard icon)
- [x] information about number of attempts, etc.
- [x] fix for apps which are closed instantly after spawn
- [x] information for user in case of sudo failure
- [x]  manual page
- [x] --help ~~& --version~~ arguments

### CODE REVIEW

**Comment by palinek** [comment]
Now for me it seems ready for use. Maybe the UI needs to polish...

**Comment by pmattern** [comment]
The problem that some applications' GUI wouldn't come up as described [here](https://github.com/lxde/lxqt-admin/pull/22#issuecomment-104407947) has indeed gone as of ff49be7 in branch wip. Interestingly enough gparted had worked with that old version of lxqt-sudo here, too, much as @luis-pereira had said.

If PCManFM-Qt gets launched via lxqt-sudo no icons are displayed in the two panes and the problem described in lxde/lxqt#639 exists as well.

Unlike gksu lxqt-sudo doesn't seem to be able to use su as backend.

Some documentation wouldn't hurt. In particular as I for one couldn't find out the purpose of lxqt-sudo-helper that quickly.
What I said about lxqt-sudo.desktop in the said comment still applies, imo.

**Comment by palinek** [comment]
> If PCManFM-Qt gets launched via lxqt-sudo no icons are displayed in the two panes and the problem described in lxde/lxqt#639 exists as well.

IMHO that's problem of pcman-qt itself, not the lxqt-sudo tool. The same is happening when invoked via plain sudo.

**Comment by paulolieuthier** [comment]
Just to confirm it, pacman works now. Great work, @palinek.

**Comment by palinek** [comment]
> What I said about lxqt-sudo.desktop in the said comment still applies, imo.

@pmattern please, commit any suggested changes, because I don't know much about .desktop files

> Some documentation wouldn't hurt. In particular as I for one couldn't find out the purpose of lxqt-sudo-helper that quickly.

created a manual page... --help (and --version) will follow

> Unlike gksu lxqt-sudo doesn't seem to be able to use su as backend.

that's true

**Comment by pmattern** [comment]
*regarding lxqt-sudo.desktop*
Launching binary lxqt-sudo without any arguments doesn't make sense, the arguments passed to lxqt-sudo are varying heavily, the [Variables](http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html#exec-variables) that can be passed to the binary stated in desktop entry files' 'Exec' line aren't helpful.
So honestly I can't see any benefit from the desktop entry file at all and would just drop it. Things would be different if launching lxqt-sudo would bring up a GUI where e. g. both an application to be run and the user to do so can be filed. But that's a whole different story.

**Comment by palinek** [comment]
> So honestly I can't see any benefit from the desktop entry file at all and would just drop it. 

You're right. There is no need to have .desktop for standalone lxqt-sudo. Particular application which needs root permisions can provide its .desktop file (with use of lxqt-sudo)

I think now we can merge/release the lxqt-sudo.... @paulolieuthier, @jleclanche, @pmattern , @Vladimir-scp what's your opinion?

**Comment by paulolieuthier** [comment]
On passworddialog.cpp, line 47, you did:
```c++
 ui->commandL->setText(argv.replaceInStrings(QRegExp(QStringLiteral("^(.*)$")), "'\\1'").join(QStringLiteral(" ")));
```
Why all that? IMO, it looks weird. The whole command between quotes would be enough.

**Comment by paulolieuthier** [comment]
Another thing, maybe it's just a matter of taste, but for me there shouldn't be a message box for lxqt-sudo usage erros. The user enters lxqt-sudo in the terminal, and in the terminal the error message should appear.

Typing the wrong password, on the other hand, happens in the dialog, and the error should appear in the dialog. Right now, there is no error feedback. Changing the dialog icon to a big red one would be nice and enough, IMO.

**Comment by palinek** [comment]
> Why all that? IMO, it looks weird. The whole command between quotes would be enough.

Just to identify all the parameters (for case white space is inside of parameter)... it's only a matter of taste. It doesn't need to be shown like that.

**Comment by paulolieuthier** [comment]
Besides my comments, it's looking and working great. I'll be using, definitely. I just find the name too long, but that's a problem.

**Comment by palinek** [comment]
> Typing the wrong password, on the other hand, happens in the dialog, and the error should appear in the dialog. Right now, there is no error feedback. 

There is a infomation about number of attempt.

**Comment by palinek** [comment]
> Another thing, maybe it's just a matter of taste, but for me there shouldn't be a message box for lxqt-sudo usage erros. The user enters lxqt-sudo in the terminal, and in the terminal the error message should appear.

In terminal you can see the output/error of sudo. I don't see a point to duplicate the information. lxqt-sudo is GUI frontend, so it notifies the user about error in GUI way.

**Comment by pmattern** [comment]
Regarding functionality I'm missing su as backend a bit as already said but aside from this I'd consider it ready for prime time, too.

Regarding an eventual release I wonder whether 'lxqt-sudo' is a suitable as name as it strongly suggests the functionality was limited to sudo. Of course this applies for now. But who knows whether the tool may be extended some time in the future? Aside from su e. g. pkexec might be considered a backend needed some day.
So I'm not sure whether the name shouldn't be changed to something reflecting the functionality in a more generic way and that doesn't focus on a certain backend that much.

Also, I'm wondering about lxqt-sudo as a component (lxde/lxqt-sudo) on its own.
It's a rather tiny tool (no criticism, that's just due to its nature). On the other hand tools like qps may very well be forked into LXQt some day.
So I wonder whether it would make sense to create a new component like e. g. lxde/lxqt-tools and put lxqt-sudo into it. Doesn't make too much sense right now as lxqt-sudo would be the only member, but could turn out to be useful some day due to the reasons stated above.

**Comment by palinek** [comment]
> So I wonder whether it would make sense to create a new component like e. g. lxde/lxqt-tools and put lxqt-sudo into it. Doesn't make too much sense right now as lxqt-sudo would be the only member, but could turn out to be useful some day due to the reasons stated above.

Actualy I put lxqt-sudo into lxqt-admin for the first time, but @jleclanche suggested to make it a standalone component.

**Comment by palinek** [comment]
> Regarding functionality I'm missing su as backend 

I don't know how that could be implemented...

**Comment by pmattern** [comment]
> I don't know how that could be implemented...

Well, I don't either. But FWIW it is implemented in gksu.
Also, not to be misunderstood, I'd find it something nice to have, not a blocker with regards to an eventual release.

**Comment by paulolieuthier** [comment]
GTM.

**Pull request merged**
