### PR TITLE
lxqt-sudo: added support for su(1) backend

### PR DESCRIPTION
**Pull request by palinek**
@pmattern you've request the su backend. Please, help with testing.

### CODE REVIEW

**Comment by pmattern** [comment]
Unfortunately this doesn't seem to work yet:
It seems commands always get option '-c' handed over that makes some of them like medit fail in the first place
```
$ lxqt-sudo --su medit 
Unknown option -c
```
Others like KWrite or Firefox (serving as dummy only of course) are silently run by the regular user invoking lxqt-sudo on the shell.

On a side note testing is pretty much impaired by lxde/lxqt#777.

Branch su_backend on Arch Linux x86_64 with LXQt checkout made on 2015-08-04.

**Comment by palinek** [comment]
> It seems commands always get option '-c' handed over that makes some of them like medit fail in the first place

..hm... the -c is given to `su` -> child executes:
```
su -c <cmd>
```

@pmattern what does `su -c medit` do on your system?

**Comment by pmattern** [comment]
>  what does su -c medit do on your system?

Works flawlessly.

**Comment by palinek** [comment]
@pmattern I've made a small change in command assembly... can you please test it now?

**Comment by pmattern** [comment]
de6c4ff doesn't seem to help either.
If a command like `lxqt-sudo --su juffed` is invoked no GUI comes up and there's no output on the shell which is just blocked. The process can't be terminated by `Ctrl+C` but only by putting it in the background and running `kill`.
`su -c <cmd>` still working flawlessly, btw.

**Comment by palinek** [comment]
> su -c <cmd> still working flawlessly, btw.

What prompt does this output for getting the password?

**Comment by pmattern** [comment]
> What prompt does this output for getting the password?
Simply `Password:`

**Comment by palinek** [comment]
@pmattern can you, please, test on your machine with the debug commit @1ca789e and report the output?

**Comment by pmattern** [comment]
Just had a look at 1ca789e on up-to-date Arch Linux x86_64, all LXQt components except `lxqt-sudo` from VCS checkout this morning:

Commit compiles flawlessly.

Using `sudo` as backend basically works flawlessly as well but still suffers from the problem described in lxde/lxqt#777.

`su` as backend still doesn't work.
On the shell I'm seeing stuff like
```
$ lxqt-sudo --su medit 
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 115
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 'P'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "P"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 'a'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Pa"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 's'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Pas"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 's'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Pass"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 'w'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Passw"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 'o'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Passwo"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 'r'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Passwor"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 't'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Passwort"
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 ':'
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 125 "Passwort:"
```
while two processes keep running
```
# ps aux | grep -i su
peter     1578  0.2  2.7 329256 28276 pts/2    Sl+  15:29   0:00 lxqt-sudo --su medit
root      1580  0.0  0.3  44900  3216 pts/4    Ss+  15:29   0:00 su -c medit
```
Invoking `su -c <some command>` still works as described above, btw.

**Comment by palinek** [comment]
@pmattern i've changed the "su" commit. Can you test it now, please?

**Comment by paulolieuthier** [comment]
@palinek, this is what I see:

```
➜  build git:(su_backend) ✗ lxqt-sudo -s gparted
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 115
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 'P'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "P"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 'a'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Pa"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 's'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Pas"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 's'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Pass"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 'w'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Passw"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 'o'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Passwo"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 'r'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Passwor"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 'd'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Password"
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 121 ':'
/home/paulo/Workspace/lxqt/lxqt-sudo/su.cpp 125 "Password:"
Password:
```

**Comment by palinek** [comment]
@paulolieuthier and? Did the GUI come up/work?

**Comment by pmattern** [comment]
c5a129f works. Tested with medit, JuffEd and GParted on Arch Linux i686 and x86_64. No remnants of that epic output
```
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 115
/usr/local/peter/lxqt-sudo-git/src/lxqt-sudo/su.cpp 121 'P'
[...]
```

Some additional notes:
Couldn't get it to play nicely with PCManFM-Qt so far, whatever I tried to set at Preferences - Advanced - Switch user command. Setting `lxqt-sudo --su %s` and selecting `Open as Root` from menu "Tool" yields a strange error message "With su backend only one argument/command is supported!" the source of which I even couldn't determine so far.
If `--su` is set only one password attempt is possible which reflects the regular behaviour of su. Yet the UI states that line `Attempt # n`. Not sure whether this could be considered confusing.
If `--su` is used and a command gets launched in background like `lxqt-sudo --su gvim &` the shell in a virtual terminal is available again only after hitting `Enter`. Obviously an absolutely minor usability issue, fixing should only be attempted with minimal to no effort IMO but may make the UX a bit more smooth.

**Comment by paulolieuthier** [comment]
@palinek sorry for the delay. It's working now.

**Comment by palinek** [comment]
> If --su is used and a command gets launched in background like lxqt-sudo --su gvim & the shell in a virtual terminal is available again only after hitting Enter.

IMO terminal is available ... just that lxqt-sudo forwards the output of child to its stderr which is connected to the terminal => when the launched child writes something you "loose" your prompt (but the shell is still ready to use). If you redirect output of lxq-sudo whereever else, your terminal will not get trashed with the output of the background process. See following examples:
- terminal trashed with the output of juffed
```
~/work/oss/lxqt/lxqt-sudo/build$ ./lxqt-sudo -s juffed &
[1] 2714
~/work/oss/lxqt/lxqt-sudo/build$ 
"[08:34:29]" "Session '/root/.config/juff/sessions/_empty_session_' opened successfully"
"[08:34:29]" "Session '/root/.config/juff/sessions/_empty_session_' was parsed successfully"
ls
CMakeCache.txt       core                          lxqt-sudo*             lxqt-sudo_el.qm  lxqt-sudo_sk.qm     Makefile                ui_passworddialog.h
CMakeFiles/          install_manifest.txt          lxqt-sudo_automoc.cpp  lxqt-sudo_it.qm  lxqt-sudo_zh_TW.qm  moc_passworddialog.cpp
cmake_install.cmake  LXQtAppTranslationLoader.cpp  lxqt-sudo_de.qm        lxqt-sudo_pl.qm  lxsu@               t.pl*
[1]+  Done                    ./lxqt-sudo -s juffed
~/work/oss/lxqt/lxqt-sudo/build$ 
```
- output redirected -> terminal clean
```
~/work/oss/lxqt/lxqt-sudo/build$ ./lxqt-sudo -s juffed > /dev/null 2>&1 &
[1] 2707
~/work/oss/lxqt/lxqt-sudo/build$ ls
CMakeCache.txt       core                          lxqt-sudo*             lxqt-sudo_el.qm  lxqt-sudo_sk.qm     Makefile                ui_passworddialog.h
CMakeFiles/          install_manifest.txt          lxqt-sudo_automoc.cpp  lxqt-sudo_it.qm  lxqt-sudo_zh_TW.qm  moc_passworddialog.cpp
cmake_install.cmake  LXQtAppTranslationLoader.cpp  lxqt-sudo_de.qm        lxqt-sudo_pl.qm  lxsu@               t.pl*
[1]+  Exit 1                  ./lxqt-sudo -s juffed > /dev/null 2>&1
~/work/oss/lxqt/lxqt-sudo/build$ 
```

**Comment by palinek** [comment]
@pmattern just pushed @54a40f7  and @dd8903d -> with these two the pcmafm-qt is running as a charm (also icons etc.).

(I remember we were discussing the unability to start pcmafm-qt by the 'Open as root'... but can't find the issue)

**Pull request merged**
